name: DevOps CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run echo command
        run: echo "CI pipeline is working!"
      - name: List files in repo
        run: ls -ld
      - name: Check OS and username
        run: |
            whoami
            pwd
            sudo systemctl status ssh
            ufw status
